import type { SectionDefinition, SectionType } from "./types";

export const SECTION_DEFINITIONS: readonly SectionDefinition[] = [
  {
    type: "navbar",
    label: "Navbar",
    description: "Brand, links and primary action",
    category: "Essentials",
    variants: [
      { id: "classic", label: "Classic" },
      { id: "center", label: "Centered" },
      { id: "boxed", label: "Boxed" },
      { id: "asymmetric", label: "Asymmetric" },
      { id: "stacked", label: "Stacked" },
      { id: "floating", label: "Floating" },
      { id: "utility", label: "Utility" },
    ],
    thumbnail: [90, 28, 54],
  },
  {
    type: "hero",
    label: "Hero",
    description: "High-impact opening section",
    category: "Essentials",
    variants: [
      { id: "split", label: "Hero Split" },
      { id: "center", label: "Hero Center" },
      { id: "spotlight", label: "Hero Spotlight" },
      { id: "explosion", label: "Hero Explosion" },
      { id: "editorial", label: "Hero Editorial" },
      { id: "showcase", label: "Hero Showcase" },
      { id: "collage", label: "Hero Collage" },
      { id: "framed", label: "Hero Framed" },
    ],
    thumbnail: [64, 88, 46],
  },
  {
    type: "features",
    label: "Features",
    description: "Product benefits and capabilities",
    category: "Content",
    variants: [
      { id: "fan", label: "Feature Fan" },
      { id: "panels", label: "Comic Panels" },
      { id: "icons", label: "Icon Grid" },
      { id: "bento", label: "Feature Bento" },
      { id: "blueprint", label: "Feature Blueprint" },
    ],
    thumbnail: [72, 72, 72],
  },
  {
    type: "bento",
    label: "Bento Grid",
    description: "Mixed-size cards for dense product stories",
    category: "Content",
    variants: [
      { id: "editorial", label: "Editorial Bento" },
      { id: "dashboard", label: "Dashboard Bento" },
      { id: "mosaic", label: "Mosaic Bento" },
    ],
    thumbnail: [92, 44, 62],
  },
  {
    type: "stats",
    label: "Stats",
    description: "Metrics, milestones and proof points",
    category: "Content",
    variants: [
      { id: "cards", label: "Stat Cards" },
      { id: "strip", label: "Stat Strip" },
      { id: "spotlight", label: "Stat Spotlight" },
    ],
    thumbnail: [58, 78, 58],
  },
  {
    type: "comparison",
    label: "Comparison",
    description: "Side-by-side product and plan comparisons",
    category: "Content",
    variants: [
      { id: "table", label: "Comparison Table" },
      { id: "scorecard", label: "Scorecard" },
    ],
    thumbnail: [86, 86, 86],
  },
  {
    type: "gallery",
    label: "Gallery",
    description: "Visual work and product stories",
    category: "Content",
    variants: [
      { id: "grid", label: "Gallery Grid" },
      { id: "featured", label: "Featured Work" },
      { id: "contact-sheet", label: "Contact Sheet" },
      { id: "polaroids", label: "Gallery Polaroids" },
      { id: "showcase", label: "Gallery Showcase" },
    ],
    thumbnail: [80, 54, 68],
  },
  {
    type: "pricing",
    label: "Pricing",
    description: "Plans, benefits and conversion",
    category: "Conversion",
    variants: [
      { id: "horizontal", label: "Horizontal Pricing" },
      { id: "panels", label: "Pricing Panels" },
      { id: "magazine", label: "Pricing Magazine" },
      { id: "comparison", label: "Plan Comparison" },
      { id: "compact", label: "Compact Pricing" },
      { id: "spotlight", label: "Pricing Spotlight" },
    ],
    thumbnail: [62, 84, 62],
  },
  {
    type: "testimonials",
    label: "Testimonials",
    description: "Customer proof and quotes",
    category: "Content",
    variants: [
      { id: "cards", label: "Review Cards" },
      { id: "speech", label: "Speech Bubbles" },
      { id: "quotes", label: "Pull Quotes" },
      { id: "wall", label: "Review Wall" },
      { id: "featured", label: "Featured Review" },
    ],
    thumbnail: [60, 78, 64],
  },
  {
    type: "faq",
    label: "FAQ",
    description: "Expandable product questions",
    category: "Content",
    variants: [
      { id: "list", label: "FAQ List" },
      { id: "numbered", label: "Numbered FAQ" },
      { id: "split", label: "FAQ Split" },
      { id: "compact", label: "FAQ Compact" },
    ],
    thumbnail: [88, 88, 88],
  },
  {
    type: "cta",
    label: "CTA",
    description: "Focused conversion moment",
    category: "Conversion",
    variants: [
      { id: "banner", label: "CTA Banner" },
      { id: "split", label: "CTA Split" },
      { id: "burst", label: "CTA Burst" },
      { id: "floating", label: "Floating CTA" },
      { id: "inline", label: "Inline CTA" },
      { id: "poster", label: "CTA Poster" },
    ],
    thumbnail: [94, 64, 38],
  },
  {
    type: "newsletter",
    label: "Newsletter",
    description: "Email capture section",
    category: "Conversion",
    variants: [
      { id: "card", label: "Signup Card" },
      { id: "strip", label: "Signup Strip" },
      { id: "split", label: "Newsletter Split" },
      { id: "coupon", label: "Coupon Signup" },
      { id: "magazine", label: "Magazine Signup" },
    ],
    thumbnail: [74, 92, 42],
  },
  {
    type: "contact",
    label: "Contact",
    description: "Inquiry form and contact details",
    category: "Conversion",
    variants: [
      { id: "centered", label: "Centered Contact" },
      { id: "split", label: "Contact Split" },
      { id: "compact", label: "Compact Contact" },
      { id: "postcard", label: "Contact Postcard" },
    ],
    thumbnail: [56, 88, 68],
  },
  {
    type: "footer",
    label: "Footer",
    description: "Site links and final signature",
    category: "Essentials",
    variants: [
      { id: "columns", label: "Footer Columns" },
      { id: "compact", label: "Compact Footer" },
      { id: "centered", label: "Centered Footer" },
      { id: "mega", label: "Mega Footer" },
      { id: "signature", label: "Signature Footer" },
      { id: "marquee", label: "Marquee Footer" },
    ],
    thumbnail: [92, 58, 76],
  },
];

export const SECTION_MAP = Object.fromEntries(
  SECTION_DEFINITIONS.map((section) => [section.type, section]),
) as Record<SectionType, SectionDefinition>;

export const CATEGORIES = ["Essentials", "Content", "Conversion"] as const;

